

@jwt = {{login.response.body.token}}
################# AUTH USER ############################
# Register user
POST http://localhost:8080/register
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@example.com",
  "password": "password",
  "role": "admin"
}

###
# @name login
# Login user
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password"
}

###
################# PRODUCT ############################
# Create product
POST http://localhost:8080/products
Content-Type: application/json
Authorization: {{jwt}}

{
  "name": "Produk 14",
  "price": 10000,
  "stock": 20
}

###

# Get products
GET http://localhost:8080/products
Authorization: {{jwt}}

###

PUT http://localhost:8080/products/1
Content-Type: application/json
Authorization: {{jwt}}

{
  "name": "Produk 2",
  "price": 20000,
  "stock": 30
}

###

DELETE http://localhost:8080/products/3
Authorization: {{jwt}}

###

################# MANAJEMEN USER ############################
# Get user
GET http://localhost:8080/users
Authorization: {{jwt}}

###
# Add user
POST http://localhost:8080/users
Authorization: {{jwt}}
Content-Type: application/json

{
  "name": "name 1",
  "email": "email213@gmail.com",
  "role": "Admin",
  "password":"password"
}

###

# Edit user
PUT http://localhost:8080/users/4
Authorization: {{jwt}}
Content-Type: application/json

{
  "name": "name 1",
  "email": "email2@gmail.com",
  "role": "admin",
  "password":"12345"
}

###

# Edit user
DELETE http://localhost:8080/users/4
Authorization: {{jwt}}

###
################# TRANSAKSI ############################
# Create transaction
POST http://localhost:8080/transactions
Content-Type: application/json
Authorization: {{jwt}}

{
  "cart": [
    { "produk": "Produk 2", "harga": 20000 },
    { "produk": "Produk 1", "harga": 10000 },
    { "produk": "Produk 1", "harga": 10000 },
    { "produk": "Product 3", "harga": 2000 },
    { "produk": "Product 3", "harga": 2000 }
  ],
  "total_harga": 44000,
  "metode_pembayaran": "Tunai",
  "waktu_transaksi": "2024-10-11T14:05:31.213"
}


###

# Get transactions
GET http://localhost:8080/transactions
Authorization: {{jwt}}
